escuela/clases/urls.py
from django.urls import path

from clases.views import get_clase, ClaseView

app_name = 'clases'
urlpatterns = [
    #path('', get_clases, name='list'),
    path('view/', ClaseView.as_view(), name='list'),
    path('<clase_id>/', get_clase, name='detail')
]

escuela/escuela/urls.py
from django.contrib import admin
from django.urls import path, include
from clases.views import get_clase
from estudiantes.views import get_estudiantes, get_estudiante

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clases/', include('clases.urls')),
    path('estudiantes/', include('estudiantes.urls'))
]

escuela/estudiantes/urls.py
from django.urls import path

from estudiantes.views import get_estudiantes, get_estudiante

app_name = 'estudiantes'
urlpatterns = [
    path('', get_estudiantes, name='list'),
    path('<estudiante_id>/', get_estudiante, name='detail')
]

escuela/clases/models.py
from django.db import models


class Clase(models.Model):
    nombre = models.CharField(max_length=50, null=True)
    creditos = models.IntegerField()
    descripcion = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.nombre

escuela/estudiantes/models.py
from django.db import models
from clases.models import Clase

class Estudiante(models.Model):
    nombre = models.CharField(max_length=100, null=True)
    correo = models.EmailField()
    telefono = models.IntegerField()
    direccion = models.CharField(max_length=100, null=True)

    clases = models.ManyToManyField(Clase, related_name='estudiantes')

    def __str__(self):
        return self.nombre

escuela/clases/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

from clases.models import Clase


def get_clase(request, clase_id):
    clase = Clase.objects.get(id=clase_id)
    estudiantes = clase.estudiantes.all()
    return render(request, 'clases/detalle.html', {'clase': clase, 'estudiantes': estudiantes})


class ClaseView(View):
    http_method_names = ['get']
    template_name = 'clases/lista.html'

    def get(self, request):
        clases = Clase.objects.all()
        context = {
            'clases': clases
        }
        return render(
            request,
            self.template_name,
            context=context
        )

escuela/estudiantes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from estudiantes.models import Estudiante


def get_estudiantes(request):
    estudiantes = Estudiante.objects.all()
    return render(request, 'estudiantes/lista.html', {'estudiantes': estudiantes})


def get_estudiante(request, estudiante_id):
    estudiante = Estudiante.objects.get(id=estudiante_id)
    # enviar un 404 cuando no existe el registro:
    # estudiante = get_object_or_404(Estudiante, id=estudiante_id)
    return render(request, 'estudiantes/detalle.html', {'estudiante': estudiante})

escuela/clases/templates/clases/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'estudiantes:list' %}" >Estudiantes</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'clases:list' %}">Clases</a>
              </li>
            </ul>

            <div class="row justify-content-center">
                <div class="col-10">
                    {% if clase %}
                      <h3 class="h3-clases">Materia: {{ clase.nombre }}</h3>
                      <h6 class="h6-clases">Lista de estudiantes inscritos:</h6>
                          <ul class="list-group">
                              {% for estudiante in estudiantes %}
                                  <li class="list-group-item">
                                      {{ estudiante.nombre }}
                                  </li>
                              {% endfor %}
                          </ul>
                    {% else %}
                        <p>No existen informacion</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

escuela/clases/templates/clases/lista.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'estudiantes:list'%}" >Estudiantes</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link active" href="{% url 'clases:list'%}">Clases</a>
              </li>
            </ul>

            <div class="container-clases">
              {% if clases %}
                  {% for clase in clases %}
                      <div class="card card-clases">
                          <div class="card-body">
                            <h5 class="card-title">{{ clase.nombre }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                Creditos: {{ clase.creditos }}
                            </h6>
                            <p class="card-text">{{ clase.descripcion }}</p>
                            <a href="{% url 'clases:detail' clase.id %}" class="card-link">Estudiantes</a>
                          </div>
                      </div>
                  {% endfor %}
              {% else %}
                    <p>No existen clases</p>
              {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

escuela/estudiantes/templates/estudiantes/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'estudiantes:list' %}" >Estudiantes</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'clases:list' %}">Clases</a>
              </li>
            </ul>

              <div class="container-estudiante-detalle">
                  <div class="col-md-8">
                      {% if estudiante %}
                          <div class="card card-estudiantes">
                              <div class="card-body card-body-estudiantes">
                                  <p class="detalle-item"><strong>Nombre:</strong> <br>{{ estudiante.nombre }}</p>
                                  <p class="detalle-item"><strong>Correo:</strong> <br>{{ estudiante.correo }}</p>
                                  <p class="detalle-item"><strong>Telefono:</strong> <br>{{ estudiante.telefono }}</p>
                                  <p class="detalle-item"><strong>Direccion: </strong> <br> {{ estudiante.direccion }}</p>
                              </div>
                          </div>
                      {% else %}
                            <p>No existe informacion</p>
                      {% endif %}
                  </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

escuela/estudiantes/templates/estudiantes/lista.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                  <a class="nav-link active" href="{% url 'estudiantes:list' %}" >Estudiantes</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'clases:list' %}">Clases</a>
              </li>
            </ul>
            <div class="container-estudiante">
              {% if estudiantes %}
                  <div class="col-10">
                      <ul class="list-group">
                          {% for estudiante in estudiantes %}
                            <li class="list-group-item container-list-item">
                                <span>{{ estudiante.nombre }}</span>
                                <a href="{% url 'estudiantes:detail' estudiante.id %}" class="btn btn-primary">Detalles</a>
                            </li>
                          {% endfor %}
                      </ul>
                  </div>
              {% else %}
                    <p>No existen estudiantes</p>
              {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

escuela/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'clases/style.css' %}">
    <link rel="stylesheet" href="{% static 'estudiantes/style.css' %}">
    <title>Escuela</title>
</head>
<body>

<!-- As a heading -->
<nav class="navbar navbar-light navbar-app">
  <span class="navbar-brand mb-0 h1">Aplicacion escuela</span>
</nav>

<div class="container first-container">
    {% block content %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>